const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'prototypes/codex-2026-09-12/review'),wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless','--no-first-run','--hide-scrollbars','--remote-debugging-port=9340','--user-data-dir='+path.join(require('os').tmpdir(),'tk-story-art-'+Date.now()),'about:blank'],{stdio:'ignore',windowsHide:true});let ws;try{
 let target;for(let i=0;i<60&&!target;i++){await wait(100);try{target=(await(await fetch('http://localhost:9340/json')).json()).find(t=>t.type==='page');}catch{}}if(!target)throw Error('Chrome unavailable');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r));let seq=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);});const send=(method,params={})=>new Promise(r=>{pending.set(++seq,r);ws.send(JSON.stringify({id:seq,method,params}));});const ev=async expression=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result?.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description);return m.result?.result?.value;};
 const viewport=async(w,h)=>send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<600});const shot=async n=>{const m=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,n+'.png'),Buffer.from(m.result.data,'base64'));};
 const scene=async id=>{await ev(`TK.ui.scrollTo(TK.timeline.findIndex(b=>b.id===${JSON.stringify(id)}));TK.engine.goTo(TK.timeline.findIndex(b=>b.id===${JSON.stringify(id)}),'init');TK.map.setMarkers(TK.engine.beat.markers,false);TK.map.relayout()`);await wait(350);};
 const click=async selector=>{const p=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+Math.min(20,r.height/2)};})()`);for(const type of ['mousePressed','mouseReleased'])await send('Input.dispatchMouseEvent',{type,x:p.x,y:p.y,button:'left',clickCount:1});await wait(150);};
 await send('Runtime.enable');await send('Page.enable');await viewport(1440,960);await send('Page.navigate',{url:'http://localhost:8778/index.html?intro=0#c7-01'});await wait(2200);
 const collision=()=>ev(`(()=>{const towers=[...document.querySelectorAll('.works-masonry')].map(e=>e.getBoundingClientRect()).filter(b=>b.width),pins=[...document.querySelectorAll('#L-pins .pin-sym')].map(e=>e.getBoundingClientRect()).filter(b=>b.width),hits=[];for(const a of towers)for(const b of pins)if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)hits.push({x:a.x,y:a.y});return{towers:towers.length,pins:pins.length,hits};})()`);
 const collisionResults=[];
 for(const id of ['c7-01','c8-03','c9-09','c10-06']){await scene(id);for(const factor of [1,.55,1.7]){await ev(`(()=>{const c=TK.engine.beat.camera,f=${factor};TK.map.flyTo([c[0]+c[2]*(1-f)/2,c[1]+c[3]*(1-f)/2,c[2]*f,c[3]*f],0);TK.map.relayout();})()`);const r=await collision();assert.ok(r.pins>0);assert.deepEqual(r.hits,[],id+' zoom '+factor);collisionResults.push({id,factor,...r});}await scene(id);await shot('art-forts-'+id);}
 await scene('c1-01');assert.equal(await ev("[...document.querySelectorAll('.works')].filter(e=>getComputedStyle(e).display!=='none').length"),0);
 await scene('c8-03');await ev("TK.worksArt.focus(['tongguan_chain'])");await wait(850);assert.ok(await ev("[...document.querySelectorAll('.works[data-id=tongguan_chain] .works-masonry')].some(e=>e.getBoundingClientRect().width>0)"));assert.deepEqual((await collision()).hits,[]);await shot('art-forts-tongguan-close');
 assert.notEqual(await ev("getComputedStyle(document.querySelector('.works-masonry')).fill"),'none');
 const fortPoint=await ev("(()=>{const e=[...document.querySelectorAll('.works[data-id=tongguan_chain] .works-masonry')].find(e=>e.getBoundingClientRect().width),r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()");
 for(const type of ['mousePressed','mouseReleased'])await send('Input.dispatchMouseEvent',{type,...fortPoint,button:'left',clickCount:1});await wait(150);
 assert.ok(await ev("!document.querySelector('#map-person-card').hidden&&document.querySelector('#map-person-card').textContent.includes('โซ่ป้อมด่านถง')"));await click('.map-person-close');

 await scene('c7-01');await ev("TK.worksArt.signal(['longyou_chain_s','longyou_chain_n'])");assert.equal(await ev("document.querySelectorAll('.works-signalling').length"),2);await wait(500);await shot('art-forts-signal');await scene('c8-03');assert.equal(await ev("document.querySelectorAll('.works-signalling').length"),0);
 await ev("document.querySelector('.works[data-id=tongguan_chain]').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});assert.ok(await ev("!document.querySelector('#map-person-card').hidden&&document.querySelector('#map-person-card').textContent.includes('โซ่ป้อมด่านถง')"));await click('.map-person-close');
 await scene('c11-05');await ev("document.querySelector('.story-art-controls[data-scene=c11-05] .art-route-picker').open=true;document.querySelector('.story-art-controls[data-scene=c11-05]').scrollIntoView({block:'center'})");await wait(300);
 assert.equal(await ev("document.querySelectorAll('.story-art-controls[data-scene=c11-05] .art-route-choice').length"),7);
 await click('.story-art-controls[data-scene=c11-05] [data-route=han_fleet_269]');assert.equal(await ev('TK.engine.beat.id'),'c11-05');assert.ok(await ev("document.querySelectorAll('#L-markers>.route-muted').length>0"));assert.equal(await ev("document.querySelectorAll('#L-markers>[data-route=han_fleet_269].route-muted').length"),0);await shot('art-six-armies-selected');
 await click('.story-art-controls[data-scene=c11-05] [data-route="station:hefei:han"]');assert.ok(await ev("document.querySelectorAll('#L-markers>[data-route=\"station:hefei:han\"]:not(.route-muted)').length>0"));
 await click('.story-art-controls[data-scene=c11-05] [data-route=""]');assert.equal(await ev("document.querySelectorAll('.route-muted').length"),0);
 await scene('c9-09');assert.equal(await ev("document.querySelectorAll('.art-grain .grain-sack:not(.grain-spent)').length"),3);assert.equal(await ev("document.querySelectorAll('.art-grain .grain-sack').length"),10);assert.ok(await ev("document.querySelector('.art-wagon')!==null"));assert.notEqual(await ev("getComputedStyle(document.querySelector('.art-wagon path')).fill"),'none');
 await ev("document.querySelector('.story-art-controls[data-scene=c9-09]').scrollIntoView({block:'center'})");await wait(250);await shot('art-grain-story');
 await scene('c9-12');assert.equal(await ev("document.querySelectorAll('.mk-portrait').length"),0);assert.equal(await ev("document.querySelectorAll('.scene-cast[data-scene=c9-12] button').length"),5);
 await ev("document.querySelector('.scene-cast[data-scene=c9-12] summary').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});assert.equal(await ev('TK.engine.beat.id'),'c9-12');assert.ok(await ev("document.querySelector('.scene-cast[data-scene=c9-12] details').open"));
 await scene('c11-06');await ev("document.querySelector('.story-art-controls[data-scene=c11-06] .art-compare').scrollIntoView({block:'center'})");await wait(250);await click('.story-art-controls[data-scene=c11-06] [data-compare=c11-10]');assert.equal(await ev('TK.engine.beat.id'),'c11-10');assert.equal(await ev("document.querySelectorAll('.mk-portrait[data-who=lukang]').length"),0);const after=await ev('TK.map.viewBox');await ev("document.querySelector('.story-art-controls[data-scene=c11-10] .art-compare').scrollIntoView({block:'center'})");await wait(250);await click('.story-art-controls[data-scene=c11-10] [data-compare=c11-06]');assert.equal(await ev('TK.engine.beat.id'),'c11-06');assert.deepEqual(await ev('TK.map.viewBox'),after);await shot('art-compare-270');
 await viewport(390,844);await scene('c7-01');assert.ok(await ev("document.querySelector('.studio-dock').getBoundingClientRect().height<75"));assert.ok(await ev("document.querySelector('#reader').getBoundingClientRect().height>200"));await click('#art-tools-menu>summary');await click('#studio-context-toggle');assert.ok(await ev("document.body.classList.contains('studio-context-open')"));await click('#art-tools-menu>summary');await click('#studio-context-toggle');assert.ok(await ev("!document.body.classList.contains('studio-context-open')"));
 for(const id of ['c7-01','c8-03','c9-09','c11-05']){await scene(id);assert.deepEqual((await collision()).hits,[],id+' mobile');assert.equal(await ev('document.documentElement.scrollWidth>innerWidth+1'),false);await shot('art-mobile-'+id);}
 await send('Page.navigate',{url:'file:///'+root.replace(/\\/g,'/')+'/index.html?intro=0#c7-01'});await wait(2200);assert.ok(await ev("document.querySelectorAll('.works-masonry').length>0"));assert.ok(await ev("typeof TK.storyArt.focusRoute==='function'"));
 const result={collisionResults,errors};fs.writeFileSync(path.join(out,'story-art-audit.json'),JSON.stringify(result,null,2));assert.equal(errors.length,0);console.log('PASS: forts avoid map symbols at 3 zoom levels, year gates, signal cleanup, fort details, six army choices, grain, comparison, mobile menu and file://.');
 }finally{ws?.close();chrome.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
