const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'prototypes/codex-2026-09-12/review'),wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless','--no-first-run','--hide-scrollbars','--remote-debugging-port=9338','--user-data-dir='+path.join(require('os').tmpdir(),'tk-main-portraits-'+Date.now()),'about:blank'],{stdio:'ignore',windowsHide:true});let ws;try{
 let target;for(let i=0;i<60&&!target;i++){await wait(100);try{target=(await(await fetch('http://localhost:9338/json')).json()).find(t=>t.type==='page');}catch{}}if(!target)throw Error('Chrome unavailable');ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r));let seq=0;const pending=new Map(),errors=[];
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);});const send=(method,params={})=>new Promise(r=>{pending.set(++seq,r);ws.send(JSON.stringify({id:seq,method,params}));});const ev=async expression=>{const m=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(m.result?.exceptionDetails)throw Error(m.result.exceptionDetails.exception?.description);return m.result?.result?.value;};
 const viewport=async(w,h)=>send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<600});const shot=async n=>{const m=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,n+'.png'),Buffer.from(m.result.data,'base64'));};
 const scene=async id=>{await ev(`TK.ui.scrollTo(TK.timeline.findIndex(b=>b.id===${JSON.stringify(id)}));TK.engine.goTo(TK.timeline.findIndex(b=>b.id===${JSON.stringify(id)}),'init');TK.map.setMarkers(TK.engine.beat.markers,false);TK.map.relayout()`);await wait(350);};
 const click=async selector=>{const p=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+Math.min(20,r.height/2)};})()`);for(const type of ['mousePressed','mouseReleased'])await send('Input.dispatchMouseEvent',{type,x:p.x,y:p.y,button:'left',clickCount:1});await wait(150);};
 await send('Runtime.enable');await send('Page.enable');await viewport(1904,980);await send('Page.navigate',{url:'http://localhost:8778/index.html?intro=0#c4-10'});await wait(2200);await scene('c4-10');await shot('main-avatars-war');
 assert.equal(await ev("document.querySelectorAll('.mk-portrait').length"),4);
 assert.deepEqual(await ev("[...document.querySelectorAll('.map-portrait-count')].map(e=>e.textContent).sort()"),['22,000','30,000','ถอย','ถอย']);
 assert.ok(Math.abs(await ev("document.querySelector('.map-portrait-rim').getBoundingClientRect().width")-64)<1);
 await ev("Promise.all([...document.querySelectorAll('.mk-portrait image')].map(e=>new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(true);im.onerror=rej;im.src=e.getAttribute('href');})))");
 await click('.mk-portrait[data-who=madai]');assert.equal(await ev('TK.mapPeople.selected'),'madai');assert.ok(await ev("!document.querySelector('#map-person-card').hidden&&document.querySelector('#map-person-card').textContent.includes('30,000')"));await shot('main-avatars-selected');
 assert.ok(Math.abs(await ev("document.querySelector('.mk-portrait.chosen .map-portrait-rim').getBoundingClientRect().width")-76)<1);assert.equal(await ev("document.querySelector('.map-person-face').getBoundingClientRect().width"),128);
 await click('.map-person-close');assert.equal(await ev('TK.mapPeople.selected'),null);
 await ev("document.querySelector('.mk-portrait[data-who=guohuai]').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});assert.equal(await ev('TK.mapPeople.selected'),'guohuai');
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});assert.equal(await ev('TK.mapPeople.selected'),null);
 await scene('c7-06');await shot('main-avatars-chencang');await scene('c1-01');assert.equal(await ev("document.querySelectorAll('.mk-event-summary').length"),0);await shot('main-event-claude');await scene('c4-10');assert.ok(await ev("document.querySelector('#map-person-card').hidden"));
 // คนในเมืองกับคนที่ถูกกล่าวถึงต้องไม่กลายเป็นตำแหน่งเดียวกันบนแผนที่
 await scene('c1-01');assert.deepEqual(await ev("[...document.querySelectorAll('.mk-portrait')].map(g=>[g.dataset.who,g.dataset.place])"),[['zhaoyun','chengdu'],['liubei','chengdu']]);
 await click('.mk-portrait[data-who=liubei]');assert.ok(await ev("document.querySelector('#map-person-card').textContent.includes('ผู้รับฟัง')"));await click('.map-person-close');
 await click('.scene-cast[data-scene=c1-01] [data-who=zhaoyun]');assert.ok(await ev("!document.querySelector('#scene-cast-role-c1-01').hidden"));assert.equal(await ev('TK.engine.beat.id'),'c1-01');
 await ev("document.querySelector('.scene-cast[data-scene=c1-01] [data-who=liubei]').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});assert.equal(await ev('TK.engine.beat.id'),'c1-01');assert.ok(await ev("document.querySelector('#scene-cast-role-c1-01').textContent.includes('ผู้รับฟัง')"));await shot('narrative-court-desktop');
 await scene('c1-06');assert.deepEqual(await ev("[...document.querySelectorAll('.mk-portrait')].map(g=>g.dataset.who)"),['zhaoyun']);
 await click('.scene-cast[data-scene=c1-06] [data-who=dengzhi]');assert.ok(await ev("document.querySelector('#scene-cast-role-c1-06').textContent.includes('ทูต')"));assert.equal(await ev("document.querySelectorAll('.mk-portrait[data-who=dengzhi]').length"),0);await shot('narrative-edicts-desktop');
 await scene('c1-08');assert.deepEqual(await ev("[...document.querySelectorAll('.mk-portrait')].map(g=>[g.dataset.who,g.dataset.place])"),[['zhangfei',''],['liubei','chengdu']]);await shot('narrative-brothers-desktop');
 const coverage=await ev(`(()=>{let count=0;const bad=[];for(const b of TK.timeline){TK.engine.goTo(TK.timeline.indexOf(b),'init');TK.map.setMarkers(b.markers,false);TK.map.relayout();const actual=[...document.querySelectorAll('.mk-portrait')].map(g=>g.dataset.who),routes=(b.markers||[]).filter(m=>m.type==='arrow'&&TK.people[m.who]).map(m=>m.who),stationed=(TK.scenePeople[b.id]||[]).filter(a=>a.place&&!routes.includes(a.who)).map(a=>a.who),expected=routes.concat(stationed);count+=actual.length;if(JSON.stringify(actual.sort())!==JSON.stringify(expected.sort()))bad.push(b.id);}return{count,bad};})()`);assert.equal(coverage.count,75);assert.deepEqual(coverage.bad,[]);
 for(const [id,who] of [['c1-08','zhangfei'],['c10-02','xiahouba'],['c9-06','caoshuang']]){await scene(id);assert.equal(await ev(`document.querySelector('.mk-portrait')?.dataset.who`),who);await click('.mk-portrait');assert.equal(await ev('TK.mapPeople.selected'),who);await shot('corrected-'+id);}
 await scene('c3-02');assert.equal(await ev("document.querySelectorAll('.mk-ticks,.mk-tick,.mk-event-summary').length"),0);await shot('corrected-supply-line');
 await scene('c1-03');assert.equal(await ev("document.querySelectorAll('#L-markers .mk-chip,#L-markers .mk-cap').length"),0);assert.equal(await ev("document.querySelectorAll('#L-markers .mk-pin').length"),5);await shot('corrected-city-labels');
 await scene('c1-06');assert.equal(await ev("document.querySelector('.mk-portrait')?.dataset.who"),'zhaoyun');assert.equal(await ev("TK.routeMeta.liubei_chengdu_hanzhong_221.commander"),'Zhao Yun');assert.equal(await ev("TK.engine.beat.markers.find(m=>m.type==='arrow').strength"),45000);await shot('corrected-royal-army');
 await scene('c1-07');assert.ok(await ev("[...document.querySelectorAll('.mk-chip-txt')].some(t=>t.textContent.includes('50,000'))"));
 await scene('c9-07');assert.equal(await ev("document.querySelector('.map-portrait-count')?.textContent"),'100,000');assert.ok(await ev("(()=>{const t=document.querySelector('.map-portrait-count').getBBox(),r=document.querySelector('.map-portrait-count-bg').getBBox();return t.x>=r.x&&t.x+t.width<=r.x+r.width;})()"));await shot('full-troop-number');
 await ev("new Promise(r=>{const s=document.createElement('script');s.src='tools/selfcheck.js';s.onload=r;document.head.append(s)})");const desktop=await ev('TK.selfcheck.all()');fs.writeFileSync(path.join(out,'main-avatars-layout.json'),JSON.stringify(desktop,null,2));
 await viewport(390,844);await scene('c4-10');await shot('main-avatars-mobile');const mobile=await ev(`(()=>{const a=[...document.querySelectorAll('.mk-portrait')],overlaps=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const A=a[i].getBoundingClientRect(),B=a[j].getBoundingClientRect();if(A.left<B.right&&A.right>B.left&&A.top<B.bottom&&A.bottom>B.top)overlaps.push([a[i].dataset.who,a[j].dataset.who]);}return{overlaps,overflow:document.documentElement.scrollWidth>innerWidth+1};})()`);assert.deepEqual(mobile.overlaps,[]);assert.equal(mobile.overflow,false);
 assert.ok(Math.abs(await ev("document.querySelector('.map-portrait-rim').getBoundingClientRect().width")-56)<1);
 await click('.mk-portrait[data-who=madai]');assert.equal(await ev('TK.mapPeople.selected'),'madai');assert.ok(Math.abs(await ev("document.querySelector('.mk-portrait.chosen .map-portrait-rim').getBoundingClientRect().width")-64)<1);assert.equal(await ev("document.querySelector('.map-person-face').getBoundingClientRect().width"),96);await shot('main-avatars-mobile-selected');
 await viewport(1904,980);await scene('c4-10');await ev("TK.map.setMarkers(TK.engine.beat.markers,true);TK.map.relayout()");await wait(1300);assert.ok(await ev("[...document.querySelectorAll('.mk-unit')].some(g=>g.querySelector('image')&&getComputedStyle(g).visibility==='visible')"));await shot('main-avatars-moving');await scene('c1-01');await wait(400);assert.equal(await ev("document.querySelectorAll('.mk-unit image').length"),0);assert.equal(await ev("document.querySelectorAll('.mk-portrait').length"),2);
 await scene('c4-10');const beforeDrag=await ev('TK.map.viewBox');const stageRect=await ev("(()=>{const r=document.querySelector('#stage').getBoundingClientRect();return{x:r.x+r.width*.7,y:r.y+r.height*.5};})()");await send('Input.dispatchMouseEvent',{type:'mousePressed',...stageRect,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:stageRect.x+65,y:stageRect.y+20,button:'left',buttons:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:stageRect.x+65,y:stageRect.y+20,button:'left',clickCount:1});await wait(250);assert.notEqual((await ev('TK.map.viewBox')).x,beforeDrag.x);await click('#studio-gallery');assert.ok(await ev("document.body.classList.contains('studio-gallery')"));assert.equal(await ev("document.querySelectorAll('.mk-portrait').length"),0);assert.ok(await ev("document.querySelector('#map-person-card').hidden"));
 await send('Page.navigate',{url:'http://localhost:8778/index.html?intro=0&ui=classic#c4-10'});await wait(1600);await scene('c4-10');await click('.mk-portrait[data-who=madai]');assert.equal(await ev('TK.mapPeople.selected'),'madai');await ev("new Promise(r=>{const s=document.createElement('script');s.src='tools/selfcheck.js';s.onload=r;document.head.append(s)})");const classic=await ev('TK.selfcheck.all()');assert.equal(classic.errors,0);
 await send('Page.navigate',{url:'file:///'+root.replace(/\\/g,'/')+'/index.html?intro=0#c4-10'});await wait(2200);await scene('c4-10');assert.equal(await ev("document.querySelectorAll('.mk-portrait').length"),4);await ev("Promise.all([...document.querySelectorAll('.mk-portrait image')].map(e=>new Promise((res,rej)=>{const i=new Image();i.onload=res;i.onerror=rej;i.src=e.getAttribute('href');})))");
 await send('Page.navigate',{url:'http://localhost:8778/index.html?intro=0#c1-01'});await wait(1600);if(await ev("!document.querySelector('#resume').hidden"))await click('#resumeNo');await viewport(390,844);
 for(const id of ['c1-01','c1-06','c1-08']){await scene(id);const layout=await ev(`(()=>{const a=[...document.querySelectorAll('.mk-portrait')].map(e=>e.getBoundingClientRect());return{overlap:a.some((A,i)=>a.slice(i+1).some(B=>A.left<B.right&&A.right>B.left&&A.top<B.bottom&&A.bottom>B.top)),overflow:document.documentElement.scrollWidth>innerWidth+1};})()`);assert.equal(layout.overlap,false,id);assert.equal(layout.overflow,false,id);await shot('narrative-'+id+'-mobile');}
 const result={coverage,desktop,classic,mobile,errors};fs.writeFileSync(path.join(out,'main-avatars-audit.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));assert.equal(errors.length,0);assert.equal(desktop.errors,0);assert.equal(desktop.warnings,0);assert.equal(classic.warnings,0);console.log('PASS: production portraits, narrative cast, real clicks, keyboard, 132-scene coverage, mobile and file:// assets.');
 }finally{ws?.close();chrome.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
